version = 1

exclude_patterns = ["src/bindings.ts"]

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["browser"]

[[transformers]]
name = "rustfmt"